db:
    image: mysql:5.7
    container_name: mysql_mv
    ports:
        - "6603:3306"
    volumes:
        - ${MYSQL_DIR}:/var/lib/mysql

    environment:
        MYSQL_ROOT_PASSWORD: mvuser
    tty: true
#
metviewer:
    image: metviewer
    container_name: metviewer_1
    ports:
    - "8080:8080"
    volumes:
      - ${METVIEWER_DATA}:/data
      - ${METVIEWER_DIR}/metviewer_output/xml:/opt/tomcat/webapps/metviewer_output/xml
      - ${METVIEWER_DIR}/metviewer_output/plots:/opt/tomcat/webapps/metviewer_output/plots
      - ${METVIEWER_DIR}/metviewer_output/data:/opt/tomcat/webapps/metviewer_output/data
      - ${METVIEWER_DIR}/metviewer_output/scripts:/opt/tomcat/webapps/metviewer_output/scripts
    links:
      - db:mysql_mv
    tty: true
web:
    depends_on:
      - db
    image: tomcat
    volumes:
      - ./target/LoginWebApp-1.war:/usr/local/tomcat/webapps/LoginWebApp-1.war
    ports:
      - '8082:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
